services:
  knowledge-service:
    build:
      context: ./knowledge-service
      dockerfile: Dockerfile.kb
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
      - LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
    volumes:
      - knowledge_data:/app/data
    networks:
      - stt-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  stt-core:
    build:
      context: ./stt-core
      dockerfile: Dockerfile.core
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      knowledge-service:
        condition: service_healthy
    networks:
      - stt-network
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # Audio device access
      - /dev/snd:/dev/snd:rw
      - /run/user/1000/pulse:/run/user/1000/pulse:rw
      - /usr/share/alsa:/usr/share/alsa:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - stt-network

volumes:
  ollama_data:
  knowledge_data:
    driver: local

networks:
  stt-network:
    driver: bridge
